### PR TITLE
Daother 8299

### PR DESCRIPTION
**Pull request by amudhakumari**

### CODE REVIEW

**Comment by epeisach** [comment]
After merging the other pull request - you have conflicts that need to be resolved.

**Comment by epeisach** [comment]
Also - why did you add wwpdb/mock-data to the repository?  That is a git submodule.  Please correct this.  Do not blindly add things to the repository.

**Comment by amudhakumari** [comment]
> Also - why did you add wwpdb/mock-data to the repository? That is a git submodule. Please correct this. Do not blindly add things to the repository.

@Ezra, I changed the tox.ini coverage as per your suggestion to 31% and wwpdb/mock-data was updated with this change and commit. Do you want me to revert back? I could add this folder to gitignore if you suggest to do so.

**Comment by amudhakumari** [comment]
> After merging the other pull request - you have conflicts that need to be resolved.

Sorry, I have resolved the conflict now. Can you please merge to develop and if possible could you do a quick test and send me some xml files to cross check? Thanks

**Pull request merged**
